services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Jovan Fidello"
        STUDENT_NIM: "00000067827"
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
